#port = 지정이 없는 경우 8080
server:
  port: 80
#JSP = MVC = prefix: /WEB-INF/views , suffix: .jsp
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
  datasource: 
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: hr
    password: happy
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        use-sql-comments: true
mybatis: 
  type-aliases-package: com.sist.web.vo
  mapper-locations: classpath:mybatis/mapper/*.xml	

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE